/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoDashboardRouteImport } from './routes/demo.dashboard'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminDomainsRouteImport } from './routes/_authenticated/admin.domains'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminWebsitesRouteImport } from './routes/_authenticated/admin.websites'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppAutomationsRouteImport } from './routes/_authenticated/app.automations'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/app.calendar'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppDomainRouteImport } from './routes/_authenticated/app.domain'
import { Route as AuthenticatedAppLaunchRouteImport } from './routes/_authenticated/app.launch'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppQuotesRouteImport } from './routes/_authenticated/app.quotes'
import { Route as AuthenticatedAppReviewsRouteImport } from './routes/_authenticated/app.reviews'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app.services'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppWebsiteRouteImport } from './routes/_authenticated/app.website'
import { Route as AuthenticatedAppWelcomeRouteImport } from './routes/_authenticated/app.welcome'
import { Route as SSlugPageRouteImport } from './routes/s.$slug.$page'
import { Route as AuthenticatedAdminClientsOrgIdRouteImport } from './routes/_authenticated/admin.clients.$orgId'
import { Route as ApiPublicJobsSiteEngineRouteImport } from './routes/api/public/jobs/site-engine'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDomainsRoute =
  AuthenticatedAdminDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWebsitesRoute =
  AuthenticatedAdminWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomationsRoute =
  AuthenticatedAppAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDomainRoute = AuthenticatedAppDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLaunchRoute = AuthenticatedAppLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppQuotesRoute = AuthenticatedAppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReviewsRoute = AuthenticatedAppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppWebsiteRoute = AuthenticatedAppWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWelcomeRoute = AuthenticatedAppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const SSlugPageRoute = SSlugPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthenticatedAdminClientsOrgIdRoute =
  AuthenticatedAdminClientsOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const ApiPublicJobsSiteEngineRoute = ApiPublicJobsSiteEngineRouteImport.update({
  id: '/api/public/jobs/site-engine',
  path: '/api/public/jobs/site-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal/webhook',
  path: '/api/public/paypal/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/p/$token': typeof PTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/demo/': typeof DemoIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/websites': typeof AuthenticatedAdminWebsitesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/automations': typeof AuthenticatedAppAutomationsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/domain': typeof AuthenticatedAppDomainRoute
  '/app/launch': typeof AuthenticatedAppLaunchRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/quotes': typeof AuthenticatedAppQuotesRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/website': typeof AuthenticatedAppWebsiteRoute
  '/app/welcome': typeof AuthenticatedAppWelcomeRoute
  '/s/$slug/$page': typeof SSlugPageRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/clients/$orgId': typeof AuthenticatedAdminClientsOrgIdRoute
  '/api/public/jobs/site-engine': typeof ApiPublicJobsSiteEngineRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/get-started': typeof GetStartedRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/p/$token': typeof PTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/demo': typeof DemoIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/websites': typeof AuthenticatedAdminWebsitesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/automations': typeof AuthenticatedAppAutomationsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/domain': typeof AuthenticatedAppDomainRoute
  '/app/launch': typeof AuthenticatedAppLaunchRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/quotes': typeof AuthenticatedAppQuotesRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/website': typeof AuthenticatedAppWebsiteRoute
  '/app/welcome': typeof AuthenticatedAppWelcomeRoute
  '/s/$slug/$page': typeof SSlugPageRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/clients/$orgId': typeof AuthenticatedAdminClientsOrgIdRoute
  '/api/public/jobs/site-engine': typeof ApiPublicJobsSiteEngineRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/p/$token': typeof PTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/demo/': typeof DemoIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/websites': typeof AuthenticatedAdminWebsitesRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/automations': typeof AuthenticatedAppAutomationsRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/domain': typeof AuthenticatedAppDomainRoute
  '/_authenticated/app/launch': typeof AuthenticatedAppLaunchRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/quotes': typeof AuthenticatedAppQuotesRoute
  '/_authenticated/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/website': typeof AuthenticatedAppWebsiteRoute
  '/_authenticated/app/welcome': typeof AuthenticatedAppWelcomeRoute
  '/s/$slug/$page': typeof SSlugPageRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/clients/$orgId': typeof AuthenticatedAdminClientsOrgIdRoute
  '/api/public/jobs/site-engine': typeof ApiPublicJobsSiteEngineRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/get-started'
    | '/industries'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/demo/dashboard'
    | '/industries/$slug'
    | '/p/$token'
    | '/s/$slug'
    | '/demo/'
    | '/industries/'
    | '/admin/clients'
    | '/admin/domains'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/websites'
    | '/app/analytics'
    | '/app/automations'
    | '/app/billing'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/domain'
    | '/app/launch'
    | '/app/leads'
    | '/app/quotes'
    | '/app/reviews'
    | '/app/services'
    | '/app/settings'
    | '/app/website'
    | '/app/welcome'
    | '/s/$slug/$page'
    | '/admin/'
    | '/app/'
    | '/admin/clients/$orgId'
    | '/api/public/jobs/site-engine'
    | '/api/public/payments/webhook'
    | '/api/public/paypal/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/get-started'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/onboarding'
    | '/demo/dashboard'
    | '/industries/$slug'
    | '/p/$token'
    | '/s/$slug'
    | '/demo'
    | '/industries'
    | '/admin/clients'
    | '/admin/domains'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/websites'
    | '/app/analytics'
    | '/app/automations'
    | '/app/billing'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/domain'
    | '/app/launch'
    | '/app/leads'
    | '/app/quotes'
    | '/app/reviews'
    | '/app/services'
    | '/app/settings'
    | '/app/website'
    | '/app/welcome'
    | '/s/$slug/$page'
    | '/admin'
    | '/app'
    | '/admin/clients/$orgId'
    | '/api/public/jobs/site-engine'
    | '/api/public/payments/webhook'
    | '/api/public/paypal/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/get-started'
    | '/industries'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/demo/dashboard'
    | '/industries/$slug'
    | '/p/$token'
    | '/s/$slug'
    | '/demo/'
    | '/industries/'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/domains'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/websites'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/automations'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/calendar'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/domain'
    | '/_authenticated/app/launch'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/quotes'
    | '/_authenticated/app/reviews'
    | '/_authenticated/app/services'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/website'
    | '/_authenticated/app/welcome'
    | '/s/$slug/$page'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/clients/$orgId'
    | '/api/public/jobs/site-engine'
    | '/api/public/payments/webhook'
    | '/api/public/paypal/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PTokenRoute: typeof PTokenRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  ApiPublicJobsSiteEngineRoute: typeof ApiPublicJobsSiteEngineRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/domains': {
      id: '/_authenticated/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AuthenticatedAdminDomainsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/websites': {
      id: '/_authenticated/admin/websites'
      path: '/websites'
      fullPath: '/admin/websites'
      preLoaderRoute: typeof AuthenticatedAdminWebsitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automations': {
      id: '/_authenticated/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AuthenticatedAppAutomationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendar': {
      id: '/_authenticated/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/domain': {
      id: '/_authenticated/app/domain'
      path: '/domain'
      fullPath: '/app/domain'
      preLoaderRoute: typeof AuthenticatedAppDomainRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/launch': {
      id: '/_authenticated/app/launch'
      path: '/launch'
      fullPath: '/app/launch'
      preLoaderRoute: typeof AuthenticatedAppLaunchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotes': {
      id: '/_authenticated/app/quotes'
      path: '/quotes'
      fullPath: '/app/quotes'
      preLoaderRoute: typeof AuthenticatedAppQuotesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reviews': {
      id: '/_authenticated/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AuthenticatedAppReviewsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/website': {
      id: '/_authenticated/app/website'
      path: '/website'
      fullPath: '/app/website'
      preLoaderRoute: typeof AuthenticatedAppWebsiteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/welcome': {
      id: '/_authenticated/app/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AuthenticatedAppWelcomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/s/$slug/$page': {
      id: '/s/$slug/$page'
      path: '/$page'
      fullPath: '/s/$slug/$page'
      preLoaderRoute: typeof SSlugPageRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/admin/clients/$orgId': {
      id: '/_authenticated/admin/clients/$orgId'
      path: '/$orgId'
      fullPath: '/admin/clients/$orgId'
      preLoaderRoute: typeof AuthenticatedAdminClientsOrgIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/api/public/jobs/site-engine': {
      id: '/api/public/jobs/site-engine'
      path: '/api/public/jobs/site-engine'
      fullPath: '/api/public/jobs/site-engine'
      preLoaderRoute: typeof ApiPublicJobsSiteEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/webhook': {
      id: '/api/public/paypal/webhook'
      path: '/api/public/paypal/webhook'
      fullPath: '/api/public/paypal/webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsOrgIdRoute: typeof AuthenticatedAdminClientsOrgIdRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsOrgIdRoute: AuthenticatedAdminClientsOrgIdRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminDomainsRoute: typeof AuthenticatedAdminDomainsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminWebsitesRoute: typeof AuthenticatedAdminWebsitesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
  AuthenticatedAdminDomainsRoute: AuthenticatedAdminDomainsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminWebsitesRoute: AuthenticatedAdminWebsitesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppAutomationsRoute: typeof AuthenticatedAppAutomationsRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppDomainRoute: typeof AuthenticatedAppDomainRoute
  AuthenticatedAppLaunchRoute: typeof AuthenticatedAppLaunchRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppQuotesRoute: typeof AuthenticatedAppQuotesRoute
  AuthenticatedAppReviewsRoute: typeof AuthenticatedAppReviewsRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppWebsiteRoute: typeof AuthenticatedAppWebsiteRoute
  AuthenticatedAppWelcomeRoute: typeof AuthenticatedAppWelcomeRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppAutomationsRoute: AuthenticatedAppAutomationsRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppDomainRoute: AuthenticatedAppDomainRoute,
  AuthenticatedAppLaunchRoute: AuthenticatedAppLaunchRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppQuotesRoute: AuthenticatedAppQuotesRoute,
  AuthenticatedAppReviewsRoute: AuthenticatedAppReviewsRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppWebsiteRoute: AuthenticatedAppWebsiteRoute,
  AuthenticatedAppWelcomeRoute: AuthenticatedAppWelcomeRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DemoRouteChildren {
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoDashboardRoute: DemoDashboardRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface SSlugRouteChildren {
  SSlugPageRoute: typeof SSlugPageRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugPageRoute: SSlugPageRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PTokenRoute: PTokenRoute,
  SSlugRoute: SSlugRouteWithChildren,
  ApiPublicJobsSiteEngineRoute: ApiPublicJobsSiteEngineRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
