/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CrmForContractorsRouteImport } from './routes/crm-for-contractors'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as GrowthAssessmentRouteImport } from './routes/growth-assessment'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WebsiteAuditRouteImport } from './routes/website-audit'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoDashboardRouteImport } from './routes/demo.dashboard'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as LocalIndexRouteImport } from './routes/local.index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsCityRouteImport } from './routes/locations.$city'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as StatesIndexRouteImport } from './routes/states.index'
import { Route as StatesStateRouteImport } from './routes/states.$state'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminDomainsRouteImport } from './routes/_authenticated/admin.domains'
import { Route as AuthenticatedAdminMonthlyRouteImport } from './routes/_authenticated/admin.monthly'
import { Route as AuthenticatedAdminOutreachRouteImport } from './routes/_authenticated/admin.outreach'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminWebsitesRouteImport } from './routes/_authenticated/admin.websites'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppAutomationsRouteImport } from './routes/_authenticated/app.automations'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/app.calendar'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppCommandRouteImport } from './routes/_authenticated/app.command'
import { Route as AuthenticatedAppDomainRouteImport } from './routes/_authenticated/app.domain'
import { Route as AuthenticatedAppLaunchRouteImport } from './routes/_authenticated/app.launch'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppQuotesRouteImport } from './routes/_authenticated/app.quotes'
import { Route as AuthenticatedAppReviewsRouteImport } from './routes/_authenticated/app.reviews'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app.services'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppWebsiteRouteImport } from './routes/_authenticated/app.website'
import { Route as AuthenticatedAppWelcomeRouteImport } from './routes/_authenticated/app.welcome'
import { Route as AuthenticatedMyIndexRouteImport } from './routes/_authenticated/my.index'
import { Route as AuthenticatedMyActivityRouteImport } from './routes/_authenticated/my.activity'
import { Route as AuthenticatedMySiteRouteImport } from './routes/_authenticated/my.site'
import { Route as AuthenticatedMyStartRouteImport } from './routes/_authenticated/my.start'
import { Route as LocalIndustryIndexRouteImport } from './routes/local.$industry.index'
import { Route as LocalIndustryStateRouteImport } from './routes/local.$industry.$state'
import { Route as SSlugPageRouteImport } from './routes/s.$slug.$page'
import { Route as AuthenticatedAdminClientsOrgIdRouteImport } from './routes/_authenticated/admin.clients.$orgId'
import { Route as ApiPublicJobsLifecycleEmailRouteImport } from './routes/api/public/jobs/lifecycle-email'
import { Route as ApiPublicJobsSiteEngineRouteImport } from './routes/api/public/jobs/site-engine'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmForContractorsRoute = CrmForContractorsRouteImport.update({
  id: '/crm-for-contractors',
  path: '/crm-for-contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthAssessmentRoute = GrowthAssessmentRouteImport.update({
  id: '/growth-assessment',
  path: '/growth-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteAuditRoute = WebsiteAuditRouteImport.update({
  id: '/website-audit',
  path: '/website-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalIndexRoute = LocalIndexRouteImport.update({
  id: '/local/',
  path: '/local/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/locations/$city',
  path: '/locations/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesIndexRoute = StatesIndexRouteImport.update({
  id: '/states/',
  path: '/states/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesStateRoute = StatesStateRouteImport.update({
  id: '/states/$state',
  path: '/states/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDomainsRoute =
  AuthenticatedAdminDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMonthlyRoute =
  AuthenticatedAdminMonthlyRouteImport.update({
    id: '/monthly',
    path: '/monthly',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOutreachRoute =
  AuthenticatedAdminOutreachRouteImport.update({
    id: '/outreach',
    path: '/outreach',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWebsitesRoute =
  AuthenticatedAdminWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomationsRoute =
  AuthenticatedAppAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommandRoute = AuthenticatedAppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDomainRoute = AuthenticatedAppDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLaunchRoute = AuthenticatedAppLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppQuotesRoute = AuthenticatedAppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReviewsRoute = AuthenticatedAppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppWebsiteRoute = AuthenticatedAppWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWelcomeRoute = AuthenticatedAppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedMyIndexRoute = AuthenticatedMyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMyRoute,
} as any)
const AuthenticatedMyActivityRoute = AuthenticatedMyActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedMyRoute,
} as any)
const AuthenticatedMySiteRoute = AuthenticatedMySiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedMyRoute,
} as any)
const AuthenticatedMyStartRoute = AuthenticatedMyStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedMyRoute,
} as any)
const LocalIndustryIndexRoute = LocalIndustryIndexRouteImport.update({
  id: '/local/$industry/',
  path: '/local/$industry/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalIndustryStateRoute = LocalIndustryStateRouteImport.update({
  id: '/local/$industry/$state',
  path: '/local/$industry/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugPageRoute = SSlugPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthenticatedAdminClientsOrgIdRoute =
  AuthenticatedAdminClientsOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const ApiPublicJobsLifecycleEmailRoute =
  ApiPublicJobsLifecycleEmailRouteImport.update({
    id: '/api/public/jobs/lifecycle-email',
    path: '/api/public/jobs/lifecycle-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsSiteEngineRoute = ApiPublicJobsSiteEngineRouteImport.update({
  id: '/api/public/jobs/site-engine',
  path: '/api/public/jobs/site-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/crm-for-contractors': typeof CrmForContractorsRoute
  '/demo': typeof DemoRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/growth-assessment': typeof GrowthAssessmentRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/share': typeof ShareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/website-audit': typeof WebsiteAuditRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/my': typeof AuthenticatedMyRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/locations/$city': typeof LocationsCityRoute
  '/p/$token': typeof PTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/states/$state': typeof StatesStateRoute
  '/compare/': typeof CompareIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/local/': typeof LocalIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/states/': typeof StatesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/monthly': typeof AuthenticatedAdminMonthlyRoute
  '/admin/outreach': typeof AuthenticatedAdminOutreachRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/websites': typeof AuthenticatedAdminWebsitesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/automations': typeof AuthenticatedAppAutomationsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/command': typeof AuthenticatedAppCommandRoute
  '/app/domain': typeof AuthenticatedAppDomainRoute
  '/app/launch': typeof AuthenticatedAppLaunchRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/quotes': typeof AuthenticatedAppQuotesRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/website': typeof AuthenticatedAppWebsiteRoute
  '/app/welcome': typeof AuthenticatedAppWelcomeRoute
  '/my/activity': typeof AuthenticatedMyActivityRoute
  '/my/site': typeof AuthenticatedMySiteRoute
  '/my/start': typeof AuthenticatedMyStartRoute
  '/local/$industry/$state': typeof LocalIndustryStateRoute
  '/s/$slug/$page': typeof SSlugPageRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/my/': typeof AuthenticatedMyIndexRoute
  '/local/$industry/': typeof LocalIndustryIndexRoute
  '/admin/clients/$orgId': typeof AuthenticatedAdminClientsOrgIdRoute
  '/api/public/jobs/lifecycle-email': typeof ApiPublicJobsLifecycleEmailRoute
  '/api/public/jobs/site-engine': typeof ApiPublicJobsSiteEngineRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/crm-for-contractors': typeof CrmForContractorsRoute
  '/get-started': typeof GetStartedRoute
  '/growth-assessment': typeof GrowthAssessmentRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/share': typeof ShareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/website-audit': typeof WebsiteAuditRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/locations/$city': typeof LocationsCityRoute
  '/p/$token': typeof PTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/states/$state': typeof StatesStateRoute
  '/compare': typeof CompareIndexRoute
  '/demo': typeof DemoIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/local': typeof LocalIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/states': typeof StatesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/monthly': typeof AuthenticatedAdminMonthlyRoute
  '/admin/outreach': typeof AuthenticatedAdminOutreachRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/websites': typeof AuthenticatedAdminWebsitesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/automations': typeof AuthenticatedAppAutomationsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/command': typeof AuthenticatedAppCommandRoute
  '/app/domain': typeof AuthenticatedAppDomainRoute
  '/app/launch': typeof AuthenticatedAppLaunchRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/quotes': typeof AuthenticatedAppQuotesRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/website': typeof AuthenticatedAppWebsiteRoute
  '/app/welcome': typeof AuthenticatedAppWelcomeRoute
  '/my/activity': typeof AuthenticatedMyActivityRoute
  '/my/site': typeof AuthenticatedMySiteRoute
  '/my/start': typeof AuthenticatedMyStartRoute
  '/local/$industry/$state': typeof LocalIndustryStateRoute
  '/s/$slug/$page': typeof SSlugPageRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/my': typeof AuthenticatedMyIndexRoute
  '/local/$industry': typeof LocalIndustryIndexRoute
  '/admin/clients/$orgId': typeof AuthenticatedAdminClientsOrgIdRoute
  '/api/public/jobs/lifecycle-email': typeof ApiPublicJobsLifecycleEmailRoute
  '/api/public/jobs/site-engine': typeof ApiPublicJobsSiteEngineRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/crm-for-contractors': typeof CrmForContractorsRoute
  '/demo': typeof DemoRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/growth-assessment': typeof GrowthAssessmentRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/share': typeof ShareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/website-audit': typeof WebsiteAuditRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/my': typeof AuthenticatedMyRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/locations/$city': typeof LocationsCityRoute
  '/p/$token': typeof PTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/states/$state': typeof StatesStateRoute
  '/compare/': typeof CompareIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/local/': typeof LocalIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/states/': typeof StatesIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/_authenticated/admin/monthly': typeof AuthenticatedAdminMonthlyRoute
  '/_authenticated/admin/outreach': typeof AuthenticatedAdminOutreachRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/websites': typeof AuthenticatedAdminWebsitesRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/automations': typeof AuthenticatedAppAutomationsRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/command': typeof AuthenticatedAppCommandRoute
  '/_authenticated/app/domain': typeof AuthenticatedAppDomainRoute
  '/_authenticated/app/launch': typeof AuthenticatedAppLaunchRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/quotes': typeof AuthenticatedAppQuotesRoute
  '/_authenticated/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/website': typeof AuthenticatedAppWebsiteRoute
  '/_authenticated/app/welcome': typeof AuthenticatedAppWelcomeRoute
  '/_authenticated/my/activity': typeof AuthenticatedMyActivityRoute
  '/_authenticated/my/site': typeof AuthenticatedMySiteRoute
  '/_authenticated/my/start': typeof AuthenticatedMyStartRoute
  '/local/$industry/$state': typeof LocalIndustryStateRoute
  '/s/$slug/$page': typeof SSlugPageRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/my/': typeof AuthenticatedMyIndexRoute
  '/local/$industry/': typeof LocalIndustryIndexRoute
  '/_authenticated/admin/clients/$orgId': typeof AuthenticatedAdminClientsOrgIdRoute
  '/api/public/jobs/lifecycle-email': typeof ApiPublicJobsLifecycleEmailRoute
  '/api/public/jobs/site-engine': typeof ApiPublicJobsSiteEngineRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/contact'
    | '/crm-for-contractors'
    | '/demo'
    | '/get-started'
    | '/growth-assessment'
    | '/industries'
    | '/manifest.webmanifest'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/share'
    | '/sitemap.xml'
    | '/terms'
    | '/website-audit'
    | '/admin'
    | '/app'
    | '/my'
    | '/onboarding'
    | '/compare/$slug'
    | '/demo/dashboard'
    | '/guides/$slug'
    | '/industries/$slug'
    | '/invite/$token'
    | '/locations/$city'
    | '/p/$token'
    | '/s/$slug'
    | '/states/$state'
    | '/compare/'
    | '/demo/'
    | '/guides/'
    | '/industries/'
    | '/local/'
    | '/locations/'
    | '/states/'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/domains'
    | '/admin/monthly'
    | '/admin/outreach'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/websites'
    | '/app/analytics'
    | '/app/automations'
    | '/app/billing'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/command'
    | '/app/domain'
    | '/app/launch'
    | '/app/leads'
    | '/app/quotes'
    | '/app/reviews'
    | '/app/services'
    | '/app/settings'
    | '/app/website'
    | '/app/welcome'
    | '/my/activity'
    | '/my/site'
    | '/my/start'
    | '/local/$industry/$state'
    | '/s/$slug/$page'
    | '/admin/'
    | '/app/'
    | '/my/'
    | '/local/$industry/'
    | '/admin/clients/$orgId'
    | '/api/public/jobs/lifecycle-email'
    | '/api/public/jobs/site-engine'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/contact'
    | '/crm-for-contractors'
    | '/get-started'
    | '/growth-assessment'
    | '/manifest.webmanifest'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/share'
    | '/sitemap.xml'
    | '/terms'
    | '/website-audit'
    | '/onboarding'
    | '/compare/$slug'
    | '/demo/dashboard'
    | '/guides/$slug'
    | '/industries/$slug'
    | '/invite/$token'
    | '/locations/$city'
    | '/p/$token'
    | '/s/$slug'
    | '/states/$state'
    | '/compare'
    | '/demo'
    | '/guides'
    | '/industries'
    | '/local'
    | '/locations'
    | '/states'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/domains'
    | '/admin/monthly'
    | '/admin/outreach'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/websites'
    | '/app/analytics'
    | '/app/automations'
    | '/app/billing'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/command'
    | '/app/domain'
    | '/app/launch'
    | '/app/leads'
    | '/app/quotes'
    | '/app/reviews'
    | '/app/services'
    | '/app/settings'
    | '/app/website'
    | '/app/welcome'
    | '/my/activity'
    | '/my/site'
    | '/my/start'
    | '/local/$industry/$state'
    | '/s/$slug/$page'
    | '/admin'
    | '/app'
    | '/my'
    | '/local/$industry'
    | '/admin/clients/$orgId'
    | '/api/public/jobs/lifecycle-email'
    | '/api/public/jobs/site-engine'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/about'
    | '/auth'
    | '/contact'
    | '/crm-for-contractors'
    | '/demo'
    | '/get-started'
    | '/growth-assessment'
    | '/industries'
    | '/manifest.webmanifest'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/share'
    | '/sitemap.xml'
    | '/terms'
    | '/website-audit'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/my'
    | '/_authenticated/onboarding'
    | '/compare/$slug'
    | '/demo/dashboard'
    | '/guides/$slug'
    | '/industries/$slug'
    | '/invite/$token'
    | '/locations/$city'
    | '/p/$token'
    | '/s/$slug'
    | '/states/$state'
    | '/compare/'
    | '/demo/'
    | '/guides/'
    | '/industries/'
    | '/local/'
    | '/locations/'
    | '/states/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/domains'
    | '/_authenticated/admin/monthly'
    | '/_authenticated/admin/outreach'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/websites'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/automations'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/calendar'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/command'
    | '/_authenticated/app/domain'
    | '/_authenticated/app/launch'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/quotes'
    | '/_authenticated/app/reviews'
    | '/_authenticated/app/services'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/website'
    | '/_authenticated/app/welcome'
    | '/_authenticated/my/activity'
    | '/_authenticated/my/site'
    | '/_authenticated/my/start'
    | '/local/$industry/$state'
    | '/s/$slug/$page'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/my/'
    | '/local/$industry/'
    | '/_authenticated/admin/clients/$orgId'
    | '/api/public/jobs/lifecycle-email'
    | '/api/public/jobs/site-engine'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CrmForContractorsRoute: typeof CrmForContractorsRoute
  DemoRoute: typeof DemoRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  GrowthAssessmentRoute: typeof GrowthAssessmentRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PortalRoute: typeof PortalRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShareRoute: typeof ShareRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WebsiteAuditRoute: typeof WebsiteAuditRoute
  CompareSlugRoute: typeof CompareSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LocationsCityRoute: typeof LocationsCityRoute
  PTokenRoute: typeof PTokenRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  StatesStateRoute: typeof StatesStateRoute
  CompareIndexRoute: typeof CompareIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  LocalIndexRoute: typeof LocalIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  StatesIndexRoute: typeof StatesIndexRoute
  LocalIndustryStateRoute: typeof LocalIndustryStateRoute
  LocalIndustryIndexRoute: typeof LocalIndustryIndexRoute
  ApiPublicJobsLifecycleEmailRoute: typeof ApiPublicJobsLifecycleEmailRoute
  ApiPublicJobsSiteEngineRoute: typeof ApiPublicJobsSiteEngineRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-for-contractors': {
      id: '/crm-for-contractors'
      path: '/crm-for-contractors'
      fullPath: '/crm-for-contractors'
      preLoaderRoute: typeof CrmForContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-assessment': {
      id: '/growth-assessment'
      path: '/growth-assessment'
      fullPath: '/growth-assessment'
      preLoaderRoute: typeof GrowthAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-audit': {
      id: '/website-audit'
      path: '/website-audit'
      fullPath: '/website-audit'
      preLoaderRoute: typeof WebsiteAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/': {
      id: '/local/'
      path: '/local'
      fullPath: '/local/'
      preLoaderRoute: typeof LocalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/locations/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/': {
      id: '/states/'
      path: '/states'
      fullPath: '/states/'
      preLoaderRoute: typeof StatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$state': {
      id: '/states/$state'
      path: '/states/$state'
      fullPath: '/states/$state'
      preLoaderRoute: typeof StatesStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/domains': {
      id: '/_authenticated/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AuthenticatedAdminDomainsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/monthly': {
      id: '/_authenticated/admin/monthly'
      path: '/monthly'
      fullPath: '/admin/monthly'
      preLoaderRoute: typeof AuthenticatedAdminMonthlyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/outreach': {
      id: '/_authenticated/admin/outreach'
      path: '/outreach'
      fullPath: '/admin/outreach'
      preLoaderRoute: typeof AuthenticatedAdminOutreachRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/websites': {
      id: '/_authenticated/admin/websites'
      path: '/websites'
      fullPath: '/admin/websites'
      preLoaderRoute: typeof AuthenticatedAdminWebsitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automations': {
      id: '/_authenticated/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AuthenticatedAppAutomationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendar': {
      id: '/_authenticated/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/command': {
      id: '/_authenticated/app/command'
      path: '/command'
      fullPath: '/app/command'
      preLoaderRoute: typeof AuthenticatedAppCommandRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/domain': {
      id: '/_authenticated/app/domain'
      path: '/domain'
      fullPath: '/app/domain'
      preLoaderRoute: typeof AuthenticatedAppDomainRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/launch': {
      id: '/_authenticated/app/launch'
      path: '/launch'
      fullPath: '/app/launch'
      preLoaderRoute: typeof AuthenticatedAppLaunchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotes': {
      id: '/_authenticated/app/quotes'
      path: '/quotes'
      fullPath: '/app/quotes'
      preLoaderRoute: typeof AuthenticatedAppQuotesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reviews': {
      id: '/_authenticated/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AuthenticatedAppReviewsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/website': {
      id: '/_authenticated/app/website'
      path: '/website'
      fullPath: '/app/website'
      preLoaderRoute: typeof AuthenticatedAppWebsiteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/welcome': {
      id: '/_authenticated/app/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AuthenticatedAppWelcomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/my/': {
      id: '/_authenticated/my/'
      path: '/'
      fullPath: '/my/'
      preLoaderRoute: typeof AuthenticatedMyIndexRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/_authenticated/my/activity': {
      id: '/_authenticated/my/activity'
      path: '/activity'
      fullPath: '/my/activity'
      preLoaderRoute: typeof AuthenticatedMyActivityRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/_authenticated/my/site': {
      id: '/_authenticated/my/site'
      path: '/site'
      fullPath: '/my/site'
      preLoaderRoute: typeof AuthenticatedMySiteRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/_authenticated/my/start': {
      id: '/_authenticated/my/start'
      path: '/start'
      fullPath: '/my/start'
      preLoaderRoute: typeof AuthenticatedMyStartRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/local/$industry/': {
      id: '/local/$industry/'
      path: '/local/$industry'
      fullPath: '/local/$industry/'
      preLoaderRoute: typeof LocalIndustryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$industry/$state': {
      id: '/local/$industry/$state'
      path: '/local/$industry/$state'
      fullPath: '/local/$industry/$state'
      preLoaderRoute: typeof LocalIndustryStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/$page': {
      id: '/s/$slug/$page'
      path: '/$page'
      fullPath: '/s/$slug/$page'
      preLoaderRoute: typeof SSlugPageRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/admin/clients/$orgId': {
      id: '/_authenticated/admin/clients/$orgId'
      path: '/$orgId'
      fullPath: '/admin/clients/$orgId'
      preLoaderRoute: typeof AuthenticatedAdminClientsOrgIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/api/public/jobs/lifecycle-email': {
      id: '/api/public/jobs/lifecycle-email'
      path: '/api/public/jobs/lifecycle-email'
      fullPath: '/api/public/jobs/lifecycle-email'
      preLoaderRoute: typeof ApiPublicJobsLifecycleEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/site-engine': {
      id: '/api/public/jobs/site-engine'
      path: '/api/public/jobs/site-engine'
      fullPath: '/api/public/jobs/site-engine'
      preLoaderRoute: typeof ApiPublicJobsSiteEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsOrgIdRoute: typeof AuthenticatedAdminClientsOrgIdRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsOrgIdRoute: AuthenticatedAdminClientsOrgIdRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminDomainsRoute: typeof AuthenticatedAdminDomainsRoute
  AuthenticatedAdminMonthlyRoute: typeof AuthenticatedAdminMonthlyRoute
  AuthenticatedAdminOutreachRoute: typeof AuthenticatedAdminOutreachRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminWebsitesRoute: typeof AuthenticatedAdminWebsitesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
  AuthenticatedAdminDomainsRoute: AuthenticatedAdminDomainsRoute,
  AuthenticatedAdminMonthlyRoute: AuthenticatedAdminMonthlyRoute,
  AuthenticatedAdminOutreachRoute: AuthenticatedAdminOutreachRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminWebsitesRoute: AuthenticatedAdminWebsitesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppAutomationsRoute: typeof AuthenticatedAppAutomationsRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppCommandRoute: typeof AuthenticatedAppCommandRoute
  AuthenticatedAppDomainRoute: typeof AuthenticatedAppDomainRoute
  AuthenticatedAppLaunchRoute: typeof AuthenticatedAppLaunchRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppQuotesRoute: typeof AuthenticatedAppQuotesRoute
  AuthenticatedAppReviewsRoute: typeof AuthenticatedAppReviewsRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppWebsiteRoute: typeof AuthenticatedAppWebsiteRoute
  AuthenticatedAppWelcomeRoute: typeof AuthenticatedAppWelcomeRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppAutomationsRoute: AuthenticatedAppAutomationsRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppCommandRoute: AuthenticatedAppCommandRoute,
  AuthenticatedAppDomainRoute: AuthenticatedAppDomainRoute,
  AuthenticatedAppLaunchRoute: AuthenticatedAppLaunchRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppQuotesRoute: AuthenticatedAppQuotesRoute,
  AuthenticatedAppReviewsRoute: AuthenticatedAppReviewsRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppWebsiteRoute: AuthenticatedAppWebsiteRoute,
  AuthenticatedAppWelcomeRoute: AuthenticatedAppWelcomeRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedMyRouteChildren {
  AuthenticatedMyActivityRoute: typeof AuthenticatedMyActivityRoute
  AuthenticatedMySiteRoute: typeof AuthenticatedMySiteRoute
  AuthenticatedMyStartRoute: typeof AuthenticatedMyStartRoute
  AuthenticatedMyIndexRoute: typeof AuthenticatedMyIndexRoute
}

const AuthenticatedMyRouteChildren: AuthenticatedMyRouteChildren = {
  AuthenticatedMyActivityRoute: AuthenticatedMyActivityRoute,
  AuthenticatedMySiteRoute: AuthenticatedMySiteRoute,
  AuthenticatedMyStartRoute: AuthenticatedMyStartRoute,
  AuthenticatedMyIndexRoute: AuthenticatedMyIndexRoute,
}

const AuthenticatedMyRouteWithChildren = AuthenticatedMyRoute._addFileChildren(
  AuthenticatedMyRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedMyRoute: typeof AuthenticatedMyRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedMyRoute: AuthenticatedMyRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DemoRouteChildren {
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoDashboardRoute: DemoDashboardRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface SSlugRouteChildren {
  SSlugPageRoute: typeof SSlugPageRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugPageRoute: SSlugPageRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CrmForContractorsRoute: CrmForContractorsRoute,
  DemoRoute: DemoRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  GrowthAssessmentRoute: GrowthAssessmentRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PortalRoute: PortalRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShareRoute: ShareRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WebsiteAuditRoute: WebsiteAuditRoute,
  CompareSlugRoute: CompareSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  LocationsCityRoute: LocationsCityRoute,
  PTokenRoute: PTokenRoute,
  SSlugRoute: SSlugRouteWithChildren,
  StatesStateRoute: StatesStateRoute,
  CompareIndexRoute: CompareIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  LocalIndexRoute: LocalIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  StatesIndexRoute: StatesIndexRoute,
  LocalIndustryStateRoute: LocalIndustryStateRoute,
  LocalIndustryIndexRoute: LocalIndustryIndexRoute,
  ApiPublicJobsLifecycleEmailRoute: ApiPublicJobsLifecycleEmailRoute,
  ApiPublicJobsSiteEngineRoute: ApiPublicJobsSiteEngineRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
